### PR TITLE
merge eth 1.9.11

### PR DESCRIPTION
**Pull request by cheng762**
merge eth 1.9.11 and fix go mod

### CODE REVIEW

**Comment by alliswell-J** [comment]
rerun tests

**Comment by benbaley** [comment]
rerun tests

**Comment by benbaley** [comment]
rerun tests

**Review by benbaley — APPROVED** [review]

**Comment by benbaley** [comment]
rerun tests

**Comment by benbaley** [comment]
rerun tests

**Comment by benbaley** [comment]
rerun tests

**Comment by benbaley** [comment]
rerun tests

**Comment by benbaley** [comment]
rerun tests

**Comment by benbaley** [comment]
rerun tests

**Comment by benbaley** [comment]
rerun tests

**Comment by benbaley** [comment]
rerun tests

**Comment by alliswell-J** [comment]
rerun tests

**Comment by benbaley** [comment]
rerun tests

**Pull request merged**
